// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_9wqlNOElFu6qFZepe7DeZz8zaKXR5ao',
    appId: '1:410341463445:web:b25d60c6677a144775129c',
    messagingSenderId: '410341463445',
    projectId: 'admin-patitas-15fc3',
    authDomain: 'admin-patitas-15fc3.firebaseapp.com',
    storageBucket: 'admin-patitas-15fc3.firebasestorage.app',
    measurementId: 'G-RM6PVMG0QZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs40ow9N3qHlw6JdU4iSow2_INyMejAm0',
    appId: '1:410341463445:android:0c9a4a97bfa92cde75129c',
    messagingSenderId: '410341463445',
    projectId: 'admin-patitas-15fc3',
    storageBucket: 'admin-patitas-15fc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2WfL0cCF4WvnqioQkenbln1-8M3x6qEI',
    appId: '1:410341463445:ios:19715f2da09cd06675129c',
    messagingSenderId: '410341463445',
    projectId: 'admin-patitas-15fc3',
    storageBucket: 'admin-patitas-15fc3.firebasestorage.app',
    iosBundleId: 'com.example.adminPatitas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_9wqlNOElFu6qFZepe7DeZz8zaKXR5ao',
    appId: '1:410341463445:web:c76eecfa951a774b75129c',
    messagingSenderId: '410341463445',
    projectId: 'admin-patitas-15fc3',
    authDomain: 'admin-patitas-15fc3.firebaseapp.com',
    storageBucket: 'admin-patitas-15fc3.firebasestorage.app',
    measurementId: 'G-RZJ7XMLKFJ',
  );

}