// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdnTOsgN8Ts-lIsdrK8GXSAN1JQ0kzURM',
    appId: '1:173118255779:web:bde80908ec8fa90b9b4516',
    messagingSenderId: '173118255779',
    projectId: 'admin-patitas',
    authDomain: 'admin-patitas.firebaseapp.com',
    databaseURL: 'https://admin-patitas-default-rtdb.firebaseio.com',
    storageBucket: 'admin-patitas.firebasestorage.app',
    measurementId: 'G-BPJBCHY089',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATEsbfA3vYCgpkocfjhXpvOsFW2QlgQH8',
    appId: '1:173118255779:android:a92af144a3db24669b4516',
    messagingSenderId: '173118255779',
    projectId: 'admin-patitas',
    databaseURL: 'https://admin-patitas-default-rtdb.firebaseio.com',
    storageBucket: 'admin-patitas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTn5wdDIENKRk_gcoZJIN2r1m064hSMpc',
    appId: '1:173118255779:ios:4dca0d98feb78d6c9b4516',
    messagingSenderId: '173118255779',
    projectId: 'admin-patitas',
    databaseURL: 'https://admin-patitas-default-rtdb.firebaseio.com',
    storageBucket: 'admin-patitas.firebasestorage.app',
    iosBundleId: 'com.example.adminPatitas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTn5wdDIENKRk_gcoZJIN2r1m064hSMpc',
    appId: '1:173118255779:ios:4dca0d98feb78d6c9b4516',
    messagingSenderId: '173118255779',
    projectId: 'admin-patitas',
    databaseURL: 'https://admin-patitas-default-rtdb.firebaseio.com',
    storageBucket: 'admin-patitas.firebasestorage.app',
    iosBundleId: 'com.example.adminPatitas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdnTOsgN8Ts-lIsdrK8GXSAN1JQ0kzURM',
    appId: '1:173118255779:web:caaca31a6a3453b09b4516',
    messagingSenderId: '173118255779',
    projectId: 'admin-patitas',
    authDomain: 'admin-patitas.firebaseapp.com',
    databaseURL: 'https://admin-patitas-default-rtdb.firebaseio.com',
    storageBucket: 'admin-patitas.firebasestorage.app',
    measurementId: 'G-7MFYVS6Q8W',
  );
}
